# Generated by Django 5.2.17 on 2026-09-07 01:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(db_index=True, max_length=32)),
                ('topic_text', models.CharField(max_length=200)),
                ('genre_slug', models.CharField(db_index=True, max_length=60)),
                ('prep_seconds', models.PositiveIntegerField()),
                ('speak_seconds', models.PositiveIntegerField()),
                ('spoken_seconds', models.PositiveIntegerField()),
                ('tz_offset', models.SmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'runs',
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
