# Generated by Django 5.2.17 on 2026-09-07 12:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segments', models.JSONField(default=list)),
                ('transcript', models.TextField(blank=True)),
                ('provider', models.CharField(blank=True, max_length=20)),
                ('audio_seconds', models.PositiveIntegerField(default=0)),
                ('opening_stall', models.FloatField(default=0)),
                ('longest_pause', models.FloatField(default=0)),
                ('awkward_pauses', models.PositiveIntegerField(default=0)),
                ('speaking_ratio', models.FloatField(default=0)),
                ('trail_off', models.FloatField(default=0)),
                ('words', models.PositiveIntegerField(default=0)),
                ('pace', models.PositiveIntegerField(default=0)),
                ('fillers', models.PositiveIntegerField(default=0)),
                ('filler_rate', models.FloatField(default=0)),
                ('crutch_words', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('run', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='runs.run')),
            ],
            options={
                'db_table': 'run_reports',
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
