# Generated by Django 5.2.17 on 2026-09-07 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runs', '0002_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='filler_words',
            field=models.JSONField(default=list),
        ),
    ]
