# Generated by Django 5.2.17 on 2026-09-07 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runs', '0003_report_filler_words'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='fillers_at_transitions',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='report',
            name='words_at',
            field=models.JSONField(default=list),
        ),
    ]
