# Generated by Django 5.2.17 on 2026-09-07 17:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("runs", "0004_report_fillers_at_transitions_report_words_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="answered",
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name="report",
            name="roles",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="report",
            name="verdict",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="report",
            name="advice",
            field=models.TextField(blank=True),
        ),
    ]
