# Generated by Django 5.2.17 on 2026-09-07 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='share_token',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
    ]
