# Generated by Django 5.2.17 on 2026-09-07 07:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=32, unique=True)),
                ('plan', models.CharField(db_index=True, max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded')], db_index=True, default='pending', max_length=20)),
                ('session_id', models.CharField(db_index=True, max_length=255)),
                ('payment_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('subscription_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('subscription_status', models.CharField(blank=True, max_length=40, null=True)),
                ('cancel_at_next_billing_date', models.BooleanField(default=False)),
                ('customer_id', models.CharField(blank=True, max_length=255, null=True)),
                ('checked_at', models.DateTimeField(blank=True, null=True)),
                ('amount_minor', models.PositiveIntegerField()),
                ('currency', models.CharField(max_length=3)),
                ('usd_cents', models.PositiveIntegerField()),
                ('fx_rate', models.FloatField(default=1.0)),
                ('ppp_multiplier', models.FloatField(default=1.0)),
                ('charged_minor', models.PositiveIntegerField(blank=True, null=True)),
                ('charged_currency', models.CharField(blank=True, max_length=3, null=True)),
                ('commission_usd_cents', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('referrer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referred_purchases', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'purchases',
                'ordering': ('-created_at', '-id'),
            },
        ),
    ]
