# Generated by Django 5.2.17 on 2026-09-06 17:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=60)),
                ('name', models.CharField(max_length=60)),
                ('icon', models.CharField(default='sparkles', max_length=32)),
                ('blurb', models.CharField(blank=True, max_length=160)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=100)),
                ('share_token', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='genres', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'genres',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220)),
                ('style', models.CharField(db_index=True, max_length=24)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=100)),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='topics.genre')),
            ],
            options={
                'db_table': 'topics',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='genre',
            constraint=models.UniqueConstraint(condition=models.Q(('owner__isnull', True)), fields=('slug',), name='genres_builtin_slug'),
        ),
        migrations.AddConstraint(
            model_name='genre',
            constraint=models.UniqueConstraint(fields=('owner', 'slug'), name='genres_owner_slug'),
        ),
        migrations.AddConstraint(
            model_name='topic',
            constraint=models.UniqueConstraint(fields=('genre', 'text'), name='topics_genre_text'),
        ),
        migrations.AddConstraint(
            model_name='topic',
            constraint=models.UniqueConstraint(fields=('genre', 'slug'), name='topics_genre_slug'),
        ),
    ]
