# Generated by Django 5.2.17 on 2026-09-09 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0002_generation'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='image',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
