# Generated by Django 5.2.17 on 2026-09-12 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0003_topic_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='mode',
            field=models.CharField(default='speak', max_length=8),
        ),
        migrations.AlterField(
            model_name='topic',
            name='text',
            field=models.CharField(max_length=1200),
        ),
    ]
